# Use an official Node.js runtime as the base image
FROM node:lts-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json /app

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["node", "/app/index.js"]

##image size is 220 MB