# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json /app

# Install dependencies
RUN npm update && npm install

# Copy the rest of the application code to the working directory
COPY . . 

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]

##image size is 912 MB